# The HONEST tension fm3 flagged: VALUE-side (foldFamily) vs COVER_LE (the geometry). Does the simple
# branch-over-Adm (option B, depth-1, codim=Mval(ROOT,T)) support cover_le, or does cover_le force the
# recursive rank-descent (schurState, the actual blow-up charts)?
print("THE TWO OBLIGATIONS the dispatcher's tree must satisfy — do they want the SAME tree shape?")
print()
print("VALUE (foldFamily_threshold_ge + achiever): needs codimsOf : ι → List ℕ with all ≥ minAdm + a")
print("  minimiser. SATISFIED by option B (flat branch-over-Adm, codim=Mval(ROOT,T)): ⨅ over Adm of Mval/2")
print("  = lambdaCore directly. The TREE SHAPE is irrelevant to foldFamily — it reads codimsOf only.")
print()
print("COVER_LE (the geometry): ∫_U |F|^{-c'} ≤ Σ_ι ∫_{unitBox} monomialIntegrand. The cells must be REAL")
print("  charts that COVER the loss locus, each landing monomial·unit via a c-o-v (pivotBlowupOn). This is")
print("  the BLOW-UP resolution — a SINGLE flat branch with arbitrary split.red does NOT provide charts.")
print("  cover_le NEEDS the actual iterated pivotBlowupOn (Case222's step-1 → step-2 → leaf), the geometry.")
print()
print("="*68)
print("THE RESOLUTION (honest answer to fm3):")
print("="*68)
print("The TREE SHAPE for VALUE and for COVER_LE need NOT be the same object, BUT in fm3's unified")
print("RouteStep they ARE (one tree feeds both isCover and isValue). So the tree must be the GEOMETRIC")
print("one (the recursive pivotBlowupOn rank-descent) — because cover_le forces real charts. The value")
print("then reads codimsOf off THAT geometric tree.")
print()
print("So the codim a node contributes = the GEOMETRIC codim of the blow-up center at that node = the")
print("cardinality of the pivot stratum = (in the ORIGINAL ambient) the Mval of the rank pattern that")
print("node's blow-up resolves. THE RANK-DESCENT TREE (candidate 2 / g195), NOT flat branch-over-Adm.")
print()
print("BUT fm3's decoupling point stands: in the recursive tree, each node's PivotWitness must witness the")
print("codim against a T∈Adm(ROOT M) (the cumulative rank pattern), with codim = the GEOMETRIC codim in the")
print("original space (= the pivot stratum cardinality, which equals Mval(ROOT, T_node) for the resolved T).")
print("The split.red (the reduced WIDTH chain) is the recursion's termination bookkeeping; the codim/witness")
print("is the geometric codim of the original-space stratum. These are LOGICALLY decoupled in the type — and")
print("the dispatcher must construct BOTH consistently: split.red = the reduced widths (Σ↓ terminates),")
print("witness.T = the cumulative rank pattern, witness.codim = Mval(ROOT, T) = the geometric pivot codim.")
print()
print("RECOMMENDATION to fm3:")
print(" - For the (2,2,2) ANCHOR + a terminating GENERAL skeleton NOW: option B-flavored but GEOMETRIC —")
print("   define schurState as a Lean def (the reduced widths M_0-1,M_1-1,M_{≥2}); the recursion is the")
print("   rank-descent (candidate 2). codim at each node = the pivot stratum's GEOMETRIC codim. This gives")
print("   cover_le real charts AND codimsOf=[4,3] for (2,2,2).")
print(" - The codim is NOT Mval(split.red, T_local) (the reduced chain's Mval — wrong, undershoots); it's")
print("   the geometric codim in the ORIGINAL space. So PivotWitness must be anchored to give that — either")
print("   carry the root M, or compute codim = pivot-stratum-cardinality directly (which = the geometric codim).")
print(" - HONEST: split.red MUST be the schurState (geometric reduced widths) for cover_le to have charts;")
print("   it is NOT free. fm3's option (1) flat-branch gives the value but NOT cover_le. Define schurState.")
