import sympy as sp
print("="*70)
print("CONSOLIDATED EXACT-ALGEBRA CERTIFICATE — achiever wedge")
print("="*70)
print()
print("[F1] Binding-axis exponent (all M): single axis (k,h)=(1,minAdm-1),")
print("     exponent at c'=minAdm/2 is (minAdm-1)-2·1·(minAdm/2) = -1. Sharp boundary.")
for mA in [3,4,6,8]:
    print(f"       minAdm={mA}: (1,{mA-1}), c'={sp.Rational(mA,2)}, exp={(mA-1)-2*sp.Rational(mA,2)}")
print()
print("[F2] (3,3,4) single weighted blow-up: F = u^2·U EXACTLY (verified pure-degree-2 in u),")
print("     U = ||tbar||^2 + ||D̄S||^2, bounded below by ||tbar||^2 on a positive-measure slice.")
print("     Jacobian u^{minAdm-1}=u^7. Feeds monomialIntegrand_lintegral_box_eq_top at (1,7). ⊤ at c'=4.")
print()
print("[F3] (2,2,2,2) single 3-coord weighting: SEARCH found 0 -- clean single blow-up FAILS for L>=3.")
print("     L>=3 needs the RECURSIVE gauge chain (F = ||Q_row0||^2 + δ^2||Q_row1||^2, Q=C2C3, recurse).")
print()
print("[F4] Multi-radial <-> single-axis transcription: blow-up s=u,a=uw converts")
print("     ∫ s^{c1-1}a^{c2-1}(s^2+a^2)^{-c'} -> u^{minAdm-1-2c'}·[finite w-integral]. Single axis (1,minAdm-1).")
print()
print("[F5] Corank immunity (Q2): U bounded below by the CLEAN block alone; coupled D̄S only ADDS.")
print("     The lower bound never touches the corank obstruction that killed hnode. ✓")
print()
print("[F6] hfin (Q3): UPPER bound = 'minAdm/2 is the GLOBAL MIN RLCT' = the headline >= direction.")
print("     CORANK-SENSITIVE: a threshold-only cover mis-resolves corank strata (3 vs 8 for (3,3,4)),")
print("     giving wrong/weak bound. Needs the correctly-resolved (coupled diag(b)) charts covering U")
print("     up to null, OR the cited analytic bound rlct >= ½·codim_min.")
print()
print("[F7] Value lane (already PROVEN, routeLayerAtlas_value): ⨅ monomialThreshold = ½·minAdm.")
print("     So the gate's VALUE is done; only the two analytic cover atoms (hdiv, hfin) remain.")
