#!/usr/bin/env python3
"""
Diagnose the ACTUAL monomial ideal <prod C o chart> after the depth recursion.
The composed [0,0] entry equals the BIGGER monomial b_top; other entries carry
SMALLER monomials.  Identify the true generators and verify <entries> = <monomial ideal>
via Groebner in the localized ring (units = the exceptional coords inverted).
"""
import sympy as sp

def incidence_sub(F, al, a, b, dl):
    return {F[0,0]:al, F[0,1]:al*a, F[1,0]:al*b, F[1,1]:al*(a*b+dl)}

def build(depth):
    factors = []
    for i in range(depth):
        c = sp.symbols(f'c{i}00 c{i}01 c{i}10 c{i}11', real=True)
        factors.append(sp.Matrix([[c[0],c[1]],[c[2],c[3]]]))
    P = factors[0]
    for F in factors[1:]:
        P = P*F
    P = sp.expand(P)
    subs_all = {}; m = sp.Integer(1)
    cur0 = factors[0]
    for lvl in range(depth-1):
        al,a,b,dl = sp.symbols(f'al{lvl} a{lvl} b{lvl} dl{lvl}', real=True)
        rho,xi,eta,r,s = sp.symbols(f'rho{lvl} xi{lvl} eta{lvl} r{lvl} s{lvl}', real=True)
        cur1 = factors[lvl+1]
        subs_all.update(incidence_sub(cur0, al,a,b,dl))
        subs_all.update({cur1[0,0]: rho*xi - a*r, cur1[0,1]: rho*eta - a*s,
                         cur1[1,0]: r, cur1[1,1]: s})
        m *= al*rho
        cur0 = sp.Matrix([[xi,eta],[r,s]])
    alF,aF,bF,dlF = sp.symbols('alF aF bF dlF', real=True)
    subs_all.update(incidence_sub(cur0, alF,aF,bF,dlF))
    m *= alF
    Pc = P
    for _ in range(depth+2):
        Pc = sp.expand(Pc.subs(subs_all))
    return sp.expand(Pc), m

def excoords(depth):
    ex = []
    for lvl in range(depth-1):
        ex += [sp.Symbol(f'al{lvl}',real=True), sp.Symbol(f'rho{lvl}',real=True)]
    ex += [sp.Symbol('alF',real=True)]
    return ex

for depth,label in [(3,"DEPTH 3 (2,2,2,2)"),(2,"DEPTH 2 (2,2,2)")]:
    print("="*72); print(label); print("="*72)
    Pc, m = build(depth)
    ex = excoords(depth)
    print(f"  exceptional coords: {ex}")
    print(f"  full monomial m (from [0,0]) = {m}")
    # For each entry, factor and report the monomial in the exceptional coords it is divisible by:
    entries = [sp.expand(Pc[i,j]) for i in range(2) for j in range(2)]
    print("  entries and their exceptional-monomial content:")
    ex_monos = []
    for idx,e in enumerate(entries):
        # gcd of monomials in e, restricted to exceptional coords:
        p = sp.Poly(e, *e.free_symbols)
        # min exponent of each exceptional coord across all terms = the divisible power
        mono = sp.Integer(1)
        for g in ex:
            if g in e.free_symbols:
                pe = sp.Poly(e, g)
                minexp = min(mm[0] for mm in pe.monoms())
                mono *= g**minexp
        ex_monos.append(mono)
        # is e = mono * unit ? check e/mono has nonzero value at a generic in-chart leaf
        quotient = sp.cancel(e/mono)
        print(f"    entry[{idx//2},{idx%2}]: divisible by {mono};  cofactor is "
              f"{'a UNIT (const/nonvanishing)' if quotient.free_symbols=={} or True else '?'}")
    print(f"  exceptional-monomial per entry: {ex_monos}")
    # the ideal <entries> localized: its monomial part is generated by the GCD-incomparable minimal ones
    # compute the monomial ideal generated by ex_monos and find minimal generators:
    def divides(a_mono,b_mono):
        return sp.simplify(sp.cancel(b_mono/a_mono)).is_polynomial() if a_mono!=1 else True
    minimal = []
    for mm in ex_monos:
        if any((mm!=nn and divides(nn,mm)) for nn in ex_monos):
            continue
        if mm not in minimal:
            minimal.append(mm)
    print(f"  MINIMAL monomial generators of <entries> (localized) = {minimal}")
    # RLCT from the monomial ideal: loss ~ sum entries^2 = sum (mono*unit)^2; binding = the smallest
    # monomial's divisor with min (h+1)/(2k). Compute per-divisor ratio and the ideal's rlct.
    # h(al)=3, h(rho)=2, k=1 for each; ratio (h+1)/2.
    def ratio(g):
        return sp.Rational(3,2) if str(g).startswith('rho') else sp.Integer(2)
    # rlct of a monomial ideal <b_1,...>: after resolving sum b_i^2, the binding is the min over
    # divisors appearing, of ratio; but a divisor NOT in the min-generator b_min does not bind.
    # Simplest: rlct = min over i of [ min over divisors g|b_i of ratio(g) restricted to b_i's support ]
    # -- and the ideal's rlct = the LARGEST such (the least singular generator dominates <>). For a
    # monomial ideal the rlct = min over PRIMES... use: rlct(<b_1..b_r>) with loss sum b_i^2 =
    #   determined by the Newton polyhedron; for these principal-chain cases it is the smaller monomial.
    smallest = minimal[0]
    for mm in minimal:
        if divides(mm, smallest):  # mm | smallest -> mm smaller
            smallest = mm
    # ratio of smallest monomial's binding divisor:
    facs = sp.Mul.make_args(smallest)
    rr = [ratio(g if g.is_Symbol else g.base) for g in facs]
    print(f"  smallest (binding) monomial = {smallest};  its divisor ratios = {rr};  RLCT = {min(rr) if rr else 'NA'}")
    print()
