import sympy as sp
# The CORRECT way to get the residual smooth-block dim: it's the rlct-binding via the ACTUAL leaf.
# Rather than reverse-engineer, compute rlctAt(||A1 A2||^2) for (3,3,3) at 0 by an INDEPENDENT exact
# method and confirm = 7/2. If = 7/2, then the MIN divisor ratio (incl any smooth block) is 7/2 =>
# no block drops below 7/2. This certifies G3.5 lower bound WITHOUT enumerating each n_block.
#
# Independent exact method: the rlct of ||A1 A2||^2 = (1/2) * lct of the determinantal-type ideal
# generated by the entries of A1 A2 -- but over R, and we want the REAL threshold. The reliable
# independent value is Aoyagi's closed form 7/2 (cross-checked against aoyagiLambda Lean #eval).
# Let me instead VERIFY n_block >= min_Adm Mval structurally for ALL leaves via the dimension identity.
#
# DIMENSION IDENTITY (the clean structural argument):
# Along a branch resolving stratum S(t), total dim N = (sum of exceptional-divisor dims) + n_block(leaf).
# Each exceptional divisor i has its own ratio r_i = (h_i+1)/(2 k_i) = Mval(t_i)/2 for the stratum it
# resolves. The leaf rlct = min over the branch's divisors of r_i, AND min with the smooth block n/2.
# The binding (=lambdaCore) is achieved at the achiever stratum's divisor. For the LOWER bound we need
# the smooth-block n/2 to not undercut. 
#
# THE STRUCTURAL ARGUMENT (Option B / smoothBlockND): a residual smooth block of dim n at a leaf
# corresponds to a nondegenerate quadratic in n fresh coords = the NORMAL SLICE to the deepest stratum
# reached on that branch. The deepest stratum reached has codim = Mval(t_deep) for some admissible t_deep
# ON that branch, and the smooth block (the unresolved transverse directions) has dim n >= codim of the
# NEXT center the branch would resolve. The smallest possible n is bounded below by the SMALLEST
# admissible codim = min_Adm Mval (because the block, if smaller, would itself BE a lower-codim stratum
# that the resolution must blow up -- contradiction with the branch being terminal).
# Concretely: a terminal smooth block means NO deeper rank-stratum lies in it; so its dim equals the
# codim of the stratum it caps = an admissible Mval >= min_Adm Mval.
#
# Let me TEST this on (2,2,2): the delta-block dim 4. Is 4 an admissible Mval for (2,2,2)? Mval(0,0)=4. 
# YES -- the dim-4 block = the S(0,0)-type transverse (the FULL rank-0 normal cone of the smaller residual
# chain). So n_block IS an admissible Mval (of the residual sub-problem), hence >= min_Adm Mval.
def Mval(M,t):
    tt=[M[0]]+list(t); L=len(M)-1
    return sum((tt[j-1]-tt[j])*(M[j]-tt[j]) for j in range(1,L+1))
print("=== TEST the structural claim 'n_block = an admissible Mval of a residual subproblem' ===")
print(f"(2,2,2) delta-block dim 4 = Mval(0,0) for (2,2,2) = {Mval((2,2,2),(0,0))}. ", end="")
print("4 is an admissible Mval >= min_Adm 3. CONSISTENT.")
print()
# For (3,3,3): the residual blocks. Resolving S(1,0): after fixing rank(A1)=1, the residual smooth core
# is the rank-1 normal slice. The smallest residual block on any branch = the deepest leaf's block.
# By the same logic, each n_block is an admissible Mval of a (sub)problem, hence >= min_Adm Mval of the
# FULL problem ONLY IF the subproblem's min_Adm Mval >= the full one. Let me CHECK this could fail:
# a residual SUBchain could have a SMALLER min_Adm Mval than the full chain -> n_block could be smaller!
# THIS IS THE REAL WORRY. Test: does any residual subchain of (3,3,3) have min_Adm Mval < 7?
print("=== THE REAL WORRY: residual SUBCHAIN min_Adm Mval < full min (7)? ===")
print("If the resolution recurses into a smaller chain whose min_Adm Mval < 7, a block there is < 7.")
# Residual subchains of (3,3,3) after peeling: reduced widths. The Schur recursion (G3.2) reduces
# (3,3,3)->(2,2,2)->(1,1,1). Their min_Adm Mval:
for M in [(3,3,3),(2,2,2),(1,1,1)]:
    from itertools import product as prod
    L=len(M)-1; adm=[]
    for t in prod(*[range(M[0]+1)]*L):
        tt=[M[0]]+list(t)
        if tt[-1]==0 and all(0<=tt[j]<=tt[j-1] for j in range(1,L+1)) and all(tt[j]<=M[j] for j in range(1,L+1)):
            adm.append(Mval(M,t))
    print(f"  chain {M}: min_Adm Mval = {min(adm)}")
print()
print("!! (2,2,2) has min_Adm Mval=3 < 7, (1,1,1) has 1 < 7. IF the (3,3,3) resolution recursed into a")
print("   (2,2,2)-subproblem and bottomed in ITS rank-1 block (dim ~3), that divisor ratio ~3/2 < 7/2")
print("   would BREAK the (3,3,3) lower bound. MUST check: does the (3,3,3) resolution actually produce")
print("   a sub-(2,2,2) blow-up with an exposed low-codim block? Or does the MONOMIAL FACTOR already")
print("   pulled out (x^2 etc.) lift every such block's ratio back above 7/2?")
