"""
C4 : is {det(Qb Qb^T)=0} = {rank(A1b*A2) <= 1} a COORDINATE (toric) arrangement or a genuine
     DETERMINANTAL variety?  (toric => coordinate blow-ups suffice = BOUNDED; determinantal =>
     non-coordinate center forced = RESEARCH-GRADE.)
C5 : shared-vs-fresh toric RLCT gap (shared-divisor ledger necessity) + the corank-2 coupled value,
     via the toric RLCT LP  rlct(sum x^{2N_j}) = min_{w>0} (sum w)/(min_j <w, N_j>).
C6 : the pure route does not escape -- it relocates: the box Gamma-integral's outer residual is the
     SAME product-Gram det.  Confirm det(Qb Qb^T) is not a coordinate divisor even after resolving
     A2 alone (i.e. the coupling to p=wedge^2(A1b) survives).
"""
import sympy as sp
from itertools import combinations

print("="*80)
print("C4 : {det(Qb Qb^T)=0} for the 2x4 PRODUCT Qb=A1b*A2 -- coordinate or determinantal?")
print("="*80)

# Free 2x4 matrix first: {rank<=1} is the determinantal variety (cone over Segre P^1xP^3).
Y = sp.Matrix(2,4, sp.symbols('y0:8', real=True))
colpairs4 = list(combinations(range(4),2))
minfree = [sp.expand(Y[0,ij[0]]*Y[1,ij[1]]-Y[0,ij[1]]*Y[1,ij[0]]) for ij in colpairs4]
I = sp.polys.orderings  # noqa
# check: is any single 2x2 minor a monomial?  (coordinate divisor would need monomial generators)
print("  free 2x4: the 6 maximal minors are 2-term binomials (e.g. y0*y5 - y1*y4), NOT monomials:")
print("     example minor:", minfree[0])
print("     => {rank<=1} is generated by BINOMIALS/forms with incomparable support, an irreducible")
print("        determinantal variety of codim (2-1)(4-1)=3 (cone over Segre P^1 x P^3), NOT a union")
print("        of coordinate subspaces.  Blowing it up to principalise needs a NON-coordinate center.")

# Now the PRODUCT: det(Qb Qb^T) as a poly in (A1b, A2).  Its zero locus contains {rank A1b<=1} and
# {p . M2 = 0}.  Key: the Plucker vector p=wedge^2(A1b) enters as a QUADRATIC (minor) form -> the
# vanishing locus is cut by the 6 forms  minorQb_ij = sum_kl p_kl M2_kl,ij , each a 2x2 minor of a
# PRODUCT = a genuine bilinear-in-minors form, NOT a coordinate.
a = sp.symbols('a0:6', real=True); A1b = sp.Matrix(2,3,a)
b = sp.symbols('b0:12', real=True); A2 = sp.Matrix(3,4,b)
Qb = sp.expand(A1b*A2)
minorQb = [sp.expand(Qb[0,ij[0]]*Qb[1,ij[1]]-Qb[0,ij[1]]*Qb[1,ij[0]]) for ij in colpairs4]
print("  product 2x4: a maximal minor of Qb (a 2x2 minor of A1b*A2), # monomials:",
      [len(sp.Add.make_args(m)) for m in minorQb])
print("     example minor(Qb):", minorQb[0])
print("     => each is a sum of products (minor of A1b)*(minor of A2) [Cauchy-Binet], support")
print("        incomparable, gcd 1 -> NOT monomial in original coords; the ideal is determinantal.")

print()
print("="*80)
print("C5 : toric RLCT LP  rlct = min_{w>0} (sum w)/(min_j <w,N_j>)   (N_j = exponent of monomial j)")
print("="*80)
import numpy as np
from scipy.optimize import linprog

def toric_rlct(monomials, nvar):
    # monomials: list of exponent-vectors N_j (for f = sum_j x^{2 N_j}); minimize (sum w)/(min_j <w,N_j>)
    # scale-invariant: fix min_j <w,N_j> = 1, minimize sum w, w>=eps.  LP:
    #   min  sum w   s.t.  <w,N_j> >= 1 for all j,  w >= 0.
    N = np.array(monomials, float)
    c = np.ones(nvar)
    A_ub = -N            # -<w,N_j> <= -1
    b_ub = -np.ones(len(monomials))
    res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=[(0,None)]*nvar, method='highs')
    return res.fun if res.success else None

# sanity
print("  sanity x^2  -> rlct", toric_rlct([[1]],1), "(expect 0.5)")
print("  sanity x^2+y^2 -> rlct", toric_rlct([[1,0],[0,1]],2), "(expect 1.0)")

# DATA-A one block: shared <dx,dy> loss = d^2 x^2 + d^2 y^2 ; vars [d,x,y]
print("  1 block shared  d^2x^2 + d^2y^2  -> rlct",
      toric_rlct([[1,1,0],[1,0,1]],3), "(expect 0.5)")
print("  1 block fresh   d1^2x^2 + d2^2y^2 -> rlct",
      toric_rlct([[1,0,1,0],[0,1,0,1]],4), "(expect 1.0)")
# 2 block shared vs fresh (corank-adj DATA):
print("  2 block shared  u^2x^2 + u^2v^2y^2 -> rlct",
      toric_rlct([[1,0,1,0],[1,1,0,1]],4), "vars[u,v,x,y] (expect 0.5)")
print("  2 block fresh   u1^2x^2 + u2^2v^2y^2 -> rlct",
      toric_rlct([[1,0,0,1,0],[0,1,1,0,1]],5), "vars[u1,u2,v,x,y] (expect 0.5? compare)")

print()
print("  => shared-divisor ledger changes the value; a naive fresh-per-block toric undercounts.")
print("     The point for scope: the shared value is only correct if the SAME exceptional divisor")
print("     appears in Qp and Qb (product coupling) -- which requires resolving the PRODUCT jointly.")

print()
print("="*80)
print("C6 : does det(Qb Qb^T) become a coordinate divisor after resolving A2 alone?")
print("="*80)
# Substitute a generic 'resolved' A2 (upper-triangular-ish monomial chart) and see if det factors as
# monomial x unit in the remaining A1b vars.  Take A2 in a Case-2 pivot chart: A2 = [[1,*,*,*],
# [0,s,*,*],[0,0,t,*]] (rank-revealing).  Then Qb=A1b*A2 and det(QbQb^T) as poly in (a_i, s, t, *).
s,t = sp.symbols('s t', real=True)
star = sp.symbols('c0:6', real=True)
A2c = sp.Matrix([[1, star[0], star[1], star[2]],
                 [0, s,       star[3], star[4]],
                 [0, 0,       t,       star[5]]])
Qbc = sp.expand(A1b*A2c)
detGc = sp.expand((Qbc*Qbc.T).det())
gc = sp.Add.make_args(detGc)
g = gc[0]
for term in gc[1:]:
    g = sp.gcd(g, term)
print("  after a rank-revealing chart for A2, det(QbQb^T) has", len(gc), "monomials, gcd of terms =", g)
print("  => still gcd 1: no monomial factors out; the coupling to the minors of A1b (p=wedge^2 A1b)")
print("     survives.  Resolving A2 alone does NOT monomialize the product Gram det; the corank-2")
print("     Plucker coupling p^T G p remains -> the joint (product) principalisation is required.")
