/-
Copyright (c) 2026. Released under Apache 2.0; see LICENSE.
-/
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.MvPolynomial.Basic

/-!
# `DLNFibre.Core.MvPolynomial.GraphIdeal` — the kernel of a multivariate `aeval` is a graph ideal

For `c : ι → R`, the kernel of the evaluation algebra map `aeval c : MvPolynomial ι R →ₐ[R] R` is
the **graph ideal** generated by the shifted coordinates `X i − C (c i)`:

> `RingHom.ker (aeval c) = Ideal.span (Set.range fun i ↦ X i − C (c i))`.

This is the multivariate analogue of `Polynomial.ker_evalRingHom`
(`RingHom.ker (evalRingHom x) = Ideal.span {X − C x}`, in `Mathlib.RingTheory.Polynomial.Ideal`),
which is absent from Mathlib v4.29 for `MvPolynomial`. The proof avoids any finite induction over
the variable type: the key is the **translation identity**
`p − C (aeval c p) ∈ span (range fun i ↦ X i − C (c i))`, proved by `MvPolynomial.induction_on`. It
holds for an *arbitrary* index type `ι` (no `Finite`/`Fintype`), dodging the universe friction of
the `Finite.induction_empty_option` route.

The eliminating consequences — the quotient iso `MvPolynomial ι R ⧸ graphIdeal c ≃ₐ[R] R`
(`graphIdealQuotientEquiv`) and primality of the graph ideal over a domain (`graphIdeal_isPrime`).

This module is pure commutative algebra. It lives in namespace `MvPolynomial` and mirrors the
Mathlib home `Mathlib.RingTheory.MvPolynomial.Ideal` (a plausible
`…/MvPolynomial/GraphIdeal.lean`), so an upstream move is a file-move with no namespace surgery.

**Dependency rule:** pure `MvPolynomial`; no DLN/RepCoord dependency. `Core` only — never import
`DLNFibre.DLN`.
-/

namespace MvPolynomial

variable {R : Type*} [CommRing R] {ι : Type*}

/-- The **graph ideal** of `c : ι → R`: the ideal of `MvPolynomial ι R` generated by the shifted
coordinates `X i − C (c i)`. Its quotient is the fibre of `aeval c` over `0`. -/
noncomputable def graphIdeal (c : ι → R) : Ideal (MvPolynomial ι R) :=
  Ideal.span (Set.range fun i ↦ X i - C (c i))

/-- Each generator `X i − C (c i)` of the graph ideal lies in `ker (aeval c)` (it evaluates to
`c i − c i = 0`). -/
theorem sub_C_mem_ker_aeval (c : ι → R) (i : ι) :
    X i - C (c i) ∈ RingHom.ker (aeval (R := R) c).toRingHom := by
  simp [RingHom.mem_ker]

/-- **The translation identity.** For *any* `p` (and any index type `ι`, no finiteness),
`p − C (aeval c p)` lies in the graph ideal: subtracting off the constant value at `c` lands in the
ideal generated by the shifted coordinates. Proved by `MvPolynomial.induction_on`; the `mul_X` step
uses `p·X i − C(v·cᵢ) = p·(X i − C cᵢ) + (p − C v)·C cᵢ` with `v = aeval c p`. -/
theorem sub_C_aeval_mem_graphIdeal (c : ι → R) (p : MvPolynomial ι R) :
    p - C (aeval c p) ∈ graphIdeal c := by
  induction p using MvPolynomial.induction_on with
  | C a => simp [graphIdeal]
  | add p q hp hq =>
      have : (p + q) - C (aeval c (p + q))
          = (p - C (aeval c p)) + (q - C (aeval c q)) := by rw [map_add, map_add]; ring
      rw [this]; exact Ideal.add_mem _ hp hq
  | mul_X p i hp =>
      have hgen : X i - C (c i) ∈ graphIdeal c :=
        Ideal.subset_span ⟨i, rfl⟩
      have hkey : (p * X i) - C (aeval c (p * X i))
          = p * (X i - C (c i)) + (p - C (aeval c p)) * C (c i) := by
        rw [map_mul, aeval_X, map_mul]
        ring
      rw [hkey]
      exact Ideal.add_mem _ (Ideal.mul_mem_left _ _ hgen) (Ideal.mul_mem_right _ _ hp)

/-- **The kernel of a multivariate `aeval` is the graph ideal.** `ker (aeval c) = span (range
fun i ↦ X i − C (c i))`, for `c : ι → R` over a commutative ring, *any* index type `ι`. The `⊇` is
the generator membership `sub_C_mem_ker_aeval`; the `⊆` is the translation identity
`sub_C_aeval_mem_graphIdeal` (if `aeval c p = 0` then `p = p − C (aeval c p) ∈ graphIdeal c`). -/
theorem ker_aeval_eq_graphIdeal (c : ι → R) :
    RingHom.ker (aeval (R := R) c).toRingHom = graphIdeal c := by
  apply le_antisymm
  · intro p hp
    rw [RingHom.mem_ker] at hp
    have h := sub_C_aeval_mem_graphIdeal c p
    rwa [show (aeval c p) = (0 : R) from hp, map_zero, sub_zero] at h
  · rw [graphIdeal, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    exact sub_C_mem_ker_aeval c i

/-- `aeval c` is surjective (it hits every constant). Used with `ker_aeval_eq_graphIdeal` to get the
quotient iso `MvPolynomial ι R ⧸ graphIdeal c ≃ₐ[R] R`. -/
theorem aeval_surjective (c : ι → R) :
    Function.Surjective (aeval (R := R) c) :=
  fun y ↦ ⟨C y, by simp⟩

/-- **The quotient by the graph ideal is the base ring.** `MvPolynomial ι R ⧸ graphIdeal c ≃ₐ[R] R`,
via `aeval c` (surjective onto constants, kernel `= graphIdeal c`). This is the elimination: the
graph ideal cuts the polynomial ring down to `R`. -/
noncomputable def graphIdealQuotientEquiv (c : ι → R) :
    (MvPolynomial ι R ⧸ graphIdeal c) ≃ₐ[R] R :=
  (Ideal.quotientEquivAlgOfEq R (ker_aeval_eq_graphIdeal c).symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective (aeval_surjective c))

/-- **The graph ideal is prime when the base ring is a domain.** `graphIdeal c` is the kernel of the
ring hom `aeval c` to the domain `R`, hence prime. -/
theorem graphIdeal_isPrime [IsDomain R] (c : ι → R) :
    (graphIdeal c).IsPrime := by
  rw [← ker_aeval_eq_graphIdeal c]
  exact RingHom.ker_isPrime (aeval (R := R) c).toRingHom

end MvPolynomial
