import sympy as sp, numpy as np
# DIRECT TEST: does the L2-style squeeze c1·Φ ≤ F ≤ c2·Φ hold for the R1 reduced-(3,3,3) node,
# with Φ = Σ_j E_j² + ‖S·A2red‖²  (E_j = (ÂA2)[0,j] the 3 regular pivot-row gens; S=Schur core)?
p,q,r,s,t,u_,v,w = sp.symbols('p q r s t u v w', real=True)
b = sp.symbols('b0:9', real=True)
Ahat = sp.Matrix([[1,p,q],[r,s,t],[u_,v,w]]); A2 = sp.Matrix(3,3,b)
M = sp.expand(Ahat*A2)
def fro2(X): return sp.expand(sum(X[i,j]**2 for i in range(X.rows) for j in range(X.cols)))
F = fro2(M)                                   # the actual loss
E = [M[0,j] for j in range(3)]                # the 3 regular pivot-row generators
S = sp.Matrix([[s-p*r, t-q*r],[v-p*u_, w-q*u_]]); A2red=A2[1:,:]
G2 = fro2(sp.expand(S*A2red))                 # the E-free Schur core
Phi = sp.expand(sum(e**2 for e in E) + G2)    # the clean comparison object
allv = (p,q,r,s,t,u_,v,w,*[b[i] for i in range(9)])
fF = sp.lambdify(allv, F, 'numpy'); fP = sp.lambdify(allv, Phi, 'numpy')
# Also confirm same zero-set: F=0 ⟺ ÂA2=0 ⟺ E=0 ∧ (lower rows)=0; Φ=0 ⟺ E=0 ∧ S·A2red=0.
# lower rows of ÂA2 = r·E-ish + S·A2red (from the g127 identity), so on E=0 lower rows = S·A2red.
# => {F=0} = {E=0, S·A2red=0} = {Φ=0}. (verify numerically the ratio stays bounded.)
print("Squeeze test F/Φ near 0 (must be bounded in [c1,c2], c1,c2>0):")
rng = np.random.default_rng(2)
for scale in [0.3,0.1,0.03,0.01]:
    X = rng.uniform(-scale,scale,(40000,17))
    args=[X[:,i] for i in range(17)]
    Fv=fF(*args); Pv=fP(*args)
    m = np.abs(Pv)>1e-16
    ratio = Fv[m]/Pv[m]
    print(f"  scale={scale}: F/Φ min={ratio.min():.4f} max={ratio.max():.4f}")
# structural check: F - Φ = (lower rows of ÂA2)² - ‖S·A2red‖². lower = E-linear + S·A2red.
# F-Φ should lie in the ideal generated by E (the regular gens) => squeeze holds structurally.
lower = M[1:,:]   # rows 1,2 of ÂA2
FmP = sp.expand(F - Phi)
# Is F-Φ in ideal (E0,E1,E2)? i.e. F-Φ vanishes on E0=E1=E2=0.
# E_j=0 means M[0,j]=0 i.e. b_j = -(p b_{3+j}+q b_{6+j}). Substitute and check F-Φ -> 0:
subE0 = {b[0]: -(p*b[3]+q*b[6]), b[1]: -(p*b[4]+q*b[7]), b[2]: -(p*b[5]+q*b[8])}
print("\n(F - Φ) restricted to {E=0} =", sp.simplify(FmP.subs(subE0)), " (0 ⟹ F-Φ ∈ ideal(E) ⟹ structural squeeze)")
