import sympy as sp
print("="*78)
print("HONEST DOMINATION: C is NOT core-nondegenerate (prod(core) is the singular DLN")
print("multiplication map).  Redo comparability WITHOUT assuming C >= c'|core|^2.")
print("="*78)
print()
print("The comparability we ACTUALLY need is |F_moved - F| <= eps*F, eps->0 at 0.")
print("F_moved - F = ∑[ (R_i + ΔR_i)^2 - R_i^2 ] = ∑[ 2 R_i ΔR_i + ΔR_i^2 ]  (C cancels: same both sides).")
print("So we need ∑(2 R_i ΔR_i + ΔR_i^2) dominated by F = ∑R_i^2 + C.   C >= 0, so F >= ∑R_i^2.")
print("=> SUFFICES: |2 R_i ΔR_i + ΔR_i^2| <= eps * ∑R_j^2.   (We can DROP C entirely from the")
print("   denominator — using only the reg-energy ∑R^2.  C's degeneracy is IRRELEVANT.)")
print()
# 2 R_i ΔR_i: |2 R_i ΔR_i| <= eps R_i^2 + (1/eps) ΔR_i^2.  Need ΔR_i^2 <= eps' ∑R^2.
# ΔR_i = (frame const)*(reg coord)*(delta) + O(delta^2).  delta = (reg,spec)-vanishing.
# So ΔR_i = (reg coord)*(small).  Is (reg coord)^2 <= C0 * ∑R^2 ?
# ∑R^2 = ∑deepestEFull^2 >= σ_min^2 |reg|^2  (PIN-1, dE(0) invertible) -- THIS still holds,
# it's about the REG directions only, NOT core.  So (reg coord)^2 <= |reg|^2 <= σ_min^{-2} ∑R^2.
print("KEY: ∑R^2 = ∑deepestEFull^2 >= σ_min(dE(0))^2 |reg|^2  (PIN-1 reg-slice invertibility).")
print("  This bounds the REG directions by ∑R^2 -- and does NOT need C or core-nondegeneracy.")
print("  ΔR_i = (frame)(reg coord)(delta),  delta->0  =>")
print("    ΔR_i^2 = (frame)^2 (reg coord)^2 delta^2 <= (frame)^2 σ_min^{-2} (∑R^2) delta^2.")
print("  => ΔR_i^2 <= [C0 delta^2] ∑R^2,  and delta^2->0 at 0  => ΔR_i^2 <= eps' ∑R^2, eps'->0.")
print("  Then 2 R_i ΔR_i: |2 R_i ΔR_i| <= 2 sqrt(R_i^2) sqrt(ΔR_i^2) <= 2 sqrt(∑R^2) sqrt(eps' ∑R^2)")
print("    = 2 sqrt(eps') ∑R^2 <= 2 sqrt(eps') F.   ->0 at 0.")
print()
print("  => |F_moved - F| <= eps F with eps = O(sqrt(delta^2)) -> 0.  TWO-SIDED comparability.")
print("  => RLCT(F_moved) = RLCT(F).   C's core-degeneracy NEVER enters the denominator. SOUND.")
print()
print("="*78)
print("WHY THIS IS THE RIGHT MECHANISM (and first-order is NOT the framing):")
print("="*78)
print(" - The atom deepestEFull_coreConstant (on-slice value-constancy) forces ΔR to carry a REG")
print("   factor (ΔR vanishes when reg=0).  PLUS delta carries its own ->0 (Θ0=0).")
print(" - PIN-1 invertibility makes ∑R^2 dominate |reg|^2, so the REG factor in ΔR is absorbed.")
print(" - The core term C is FIXED both sides and only used as C>=0 (F >= ∑R^2).  Its singularity")
print("   (the whole DLN content) is sidestepped -- it is NOT in the domination denominator.")
print(" - Mechanism = Watanabe two-sided comparability, NOT a diffeo, NOT 'first-order suffices'.")
print("   First-order (∂E/∂core(0)=0) is NECESSARY (gives ΔR no constant-in-reg part) but the")
print("   load-bearing extra is: ΔR carries BOTH a reg factor (atom) AND delta->0 (Θ0=0), and")
print("   ∑R^2 dominates reg (PIN-1).  That triple is what closes it.")
