import sympy as sp
print("="*78)
print("π̃ STRICT-DERIV INVERTIBILITY: is regStraightenTotalCLM2(D_E) ∘ D(coreAbsorb.symm) an ISO at 0?")
print("="*78)
print()
print("Structure: π̃ = regStraightenOf2(E_full) ∘ coreAbsorb.symm, E_full = E∘coreAbsorb.symm.")
print("Dπ̃(0) = regStraightenTotalCLM2(D_E) ∘ D(coreAbsorb.symm)(0).")
print("regStraightenTotalCLM2(D_E): δ=(δr,δc,δs) ↦ (D_E·δ, δc, δs)   [reg replaced by D_E·δ; core,spec id]")
print()
print("So as a block matrix (rows out=reg/core/spec, cols in=reg/core/spec):")
print("  regStraightenTotalCLM2(D_E) = [[ D_E|reg, D_E|core, D_E|spec ],")
print("                                 [   0,       I,        0      ],")
print("                                 [   0,       0,        I      ]]")
print("  det = det(D_E|reg).   INVERTIBLE  iff  D_E|reg is invertible (the reg-block F).")
print()
print("The atom ∂E/∂core(0)=0 sets D_E|core = 0 — this makes the matrix block-LOWER-trivial in the")
print("core column, but det is STILL det(D_E|reg) regardless (the core column only affects rows that")
print("are 0 below the diagonal).  So the atom does NOT change det; det = det(D_E|reg).")
print("  => atom degeneracy is IRRELEVANT to invertibility of regStraightenTotalCLM2.")
print()
# Verify: build the CLM matrix symbolically and confirm det = det(F) regardless of D_E|core.
r,c,s = 2,2,2  # block dims (toy: reg=core=spec=2 dims)
F = sp.Matrix(r,r, lambda i,j: sp.Symbol(f'F{i}{j}'))      # D_E|reg
G = sp.Matrix(r,c, lambda i,j: sp.Symbol(f'G{i}{j}'))      # D_E|core (atom => =0)
K = sp.Matrix(r,s, lambda i,j: sp.Symbol(f'K{i}{j}'))      # D_E|spec
# regStraightenTotalCLM2(D_E): out=(D_E·δ, δc, δs).  Matrix (r+c+s)x(r+c+s):
top = F.row_join(G).row_join(K)
mid = sp.zeros(c,r).row_join(sp.eye(c)).row_join(sp.zeros(c,s))
bot = sp.zeros(s,r).row_join(sp.zeros(s,c)).row_join(sp.eye(s))
M = top.col_join(mid).col_join(bot)
detM = sp.simplify(M.det())
print("det(regStraightenTotalCLM2) symbolic =", detM, " (= det F, independent of G,K)")
print("  with atom G=0:", sp.simplify(M.subs({G[i,j]:0 for i in range(r) for j in range(c)}).det()))
print()
print("=> regStraightenTotalCLM2(D_E) INVERTIBLE  <=>  F = D_E|reg invertible.  Atom IRRELEVANT.")
print("   And D(coreAbsorb.symm)(0) is invertible (core-shear, det 1).  Composite of two isos = ISO.")
