/-
Copyright (c) 2026. Released under Apache 2.0; see LICENSE.
-/
import Mathlib.LinearAlgebra.Matrix.MvPolynomial
import Mathlib.RingTheory.Ideal.Span

/-!
# `Matrix` — the minor-determinant polynomial and the determinantal ideal of minors

The coordinate ring of the space of `p × q` matrices over a commutative ring `R` is
`MvPolynomial (Fin p × Fin q) R`, with the **generic matrix** `Matrix.mvPolynomialX` whose `(i, j)`
entry is the coordinate variable `X (i, j)`. This file packages two general matrix/determinantal
objects on top of it:

* **The minor-determinant polynomial** `Matrix.detMinorPoly s t` — the determinant of the `(s, t)`
  minor of the generic matrix. Evaluating it at a point `M` (the assignment `X (i, j) ↦ M i j`)
  gives the minor determinant `(M.submatrix s t).det` (`Matrix.eval_detMinorPoly`). So the locus
  where the `(s, t)` minor is invertible is the principal open `D(detMinorPoly s t)` of the ring.

* **The determinantal ideal** `Matrix.determinantalIdeal p q R N` — the ideal of `MvPolynomial`
  generated by all order-`N` minors (`detMinorPoly` over `N`-element row/column selectors). Its
  vanishing locus is the rank-`< N` locus: a point `M` lies in it (with `N = r + 1`) exactly when
  every `(r+1)`-minor of `M` vanishes, i.e. `M.rank ≤ r`. (That rank-locus equivalence is *not*
  proved here — it belongs with the rank-stratum API; this file supplies the ideal and its
  generators only.) Mathlib v4.29 has **no** determinantal ideal, so this object is new.

These are general matrix/`MvPolynomial` facts over an arbitrary `CommRing`; they live in the bare
`Matrix` namespace, mirroring the Mathlib home `Mathlib.LinearAlgebra.Matrix.MvPolynomial` of
`Matrix.mvPolynomialX`, so an eventual upstream move is a file-move with no namespace surgery.

**Dependency rule:** network-free `Core` — never import `DLNFibre.DLN`.
-/

namespace Matrix

open MvPolynomial

variable {R : Type*} [CommRing R] {p q r N : ℕ}

/-- **The minor-determinant polynomial** `detMinorPoly s t : MvPolynomial (Fin p × Fin q) R`: the
determinant of the `(s, t)` minor of the **generic matrix** `Matrix.mvPolynomialX` (entries the
coordinate variables `X (i, j)`). Its evaluation at a point `M` is `(M.submatrix s t).det`
(`eval_detMinorPoly`), so the locus where the `(s, t)` minor is invertible is the principal open
`D(detMinorPoly s t)` of the matrix coordinate ring. -/
noncomputable def detMinorPoly (s : Fin r → Fin p) (t : Fin r → Fin q) :
    MvPolynomial (Fin p × Fin q) R :=
  ((Matrix.mvPolynomialX (Fin p) (Fin q) R).submatrix s t).det

/-- **The minor polynomial evaluates to the minor determinant.** Evaluating `detMinorPoly s t` at
the point `M` (the assignment `X (i, j) ↦ M i j`) gives `(M.submatrix s t).det`. So membership of
`M` in the per-minor chart (the `(s, t)` minor invertible) is equivalent to
`MvPolynomial.eval (fun ij ↦ M ij.1 ij.2) (detMinorPoly s t)` being a unit — the chart is the
principal open `D(detMinorPoly s t)`. -/
theorem eval_detMinorPoly (M : Matrix (Fin p) (Fin q) R)
    (s : Fin r → Fin p) (t : Fin r → Fin q) :
    MvPolynomial.eval (fun ij ↦ M ij.1 ij.2) (detMinorPoly (R := R) s t)
      = (M.submatrix s t).det := by
  -- `eval e` is a ring hom; it commutes with `det` (`RingHom.map_det`). The mapped minor matrix
  -- is `M.submatrix s t`: `map` commutes with `submatrix`, and `eval e` sends the generic matrix
  -- `mvPolynomialX` to `M` (`mvPolynomialX_mapMatrix_eval`).
  have hmap : ((Matrix.mvPolynomialX (Fin p) (Fin q) R).submatrix s t).map
      (MvPolynomial.eval fun ij ↦ M ij.1 ij.2) = M.submatrix s t := by
    rw [← Matrix.submatrix_map]
    -- the RECTANGULAR generic matrix maps to `M` under `eval e = eval₂ id e`
    -- (`mvPolynomialX_map_eval₂`); `submatrix` then matches.
    congr 1
    rw [MvPolynomial.eval, MvPolynomial.coe_eval₂Hom]
    exact Matrix.mvPolynomialX_map_eval₂ (RingHom.id R) M
  rw [detMinorPoly, RingHom.map_det, RingHom.mapMatrix_apply, hmap]

/-! ## The determinantal ideal of order-`N` minors -/

/-- **The determinantal ideal** `determinantalIdeal p q R N`: the ideal of
`MvPolynomial (Fin p × Fin q) R` generated by all order-`N` minors of the generic `p × q` matrix
(`detMinorPoly s t` ranging over `N`-element row selectors `s : Fin N → Fin p` and column selectors
`t : Fin N → Fin q`). Its vanishing locus is the rank-`< N` locus: a point `M` lies in it exactly
when every `N × N` minor of `M` vanishes (so for `N = r + 1`, when `M.rank ≤ r`). Absent in Mathlib
v4.29. (The rank-locus equivalence is proved with the rank-stratum API, not here.) -/
noncomputable def determinantalIdeal (p q : ℕ) (R : Type*) [CommRing R] (N : ℕ) :
    Ideal (MvPolynomial (Fin p × Fin q) R) :=
  Ideal.span (Set.range fun st : (Fin N → Fin p) × (Fin N → Fin q) ↦ detMinorPoly st.1 st.2)

/-- **Every order-`N` minor lies in the determinantal ideal.** The generators of
`determinantalIdeal p q R N` are exactly the order-`N` minor polynomials `detMinorPoly s t`, so each
such minor is a member. -/
theorem detMinorPoly_mem_determinantalIdeal (s : Fin N → Fin p) (t : Fin N → Fin q) :
    detMinorPoly (R := R) s t ∈ determinantalIdeal p q R N :=
  Ideal.subset_span ⟨(s, t), rfl⟩

/-- **The determinantal ideal is the span of its minor generators.** The generating set is the range
of `detMinorPoly` over all order-`N` row/column selectors; restated as an explicit `Ideal.span` for
downstream `span_le` / membership reasoning. -/
theorem determinantalIdeal_eq_span (p q : ℕ) (R : Type*) [CommRing R] (N : ℕ) :
    determinantalIdeal p q R N =
      Ideal.span (Set.range fun st : (Fin N → Fin p) × (Fin N → Fin q) ↦
        detMinorPoly st.1 st.2) :=
  rfl

/-- **The determinantal ideal is contained in any ideal holding every order-`N` minor.** A clean
`span_le`-flavoured criterion: to show `determinantalIdeal p q R N ≤ I` it suffices that every
order-`N` minor polynomial lies in `I`. -/
theorem determinantalIdeal_le_iff {I : Ideal (MvPolynomial (Fin p × Fin q) R)} :
    determinantalIdeal p q R N ≤ I ↔
      ∀ (s : Fin N → Fin p) (t : Fin N → Fin q), detMinorPoly (R := R) s t ∈ I := by
  rw [determinantalIdeal, Ideal.span_le, Set.range_subset_iff]
  exact ⟨fun h s t ↦ h (s, t), fun h st ↦ h st.1 st.2⟩

end Matrix
