import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.RingTheory.Ideal.BigOperators

/-!
# Matrix-entry ideals for Aoyagi reductions

This file records elementary ideal algebra for ideals generated by matrix
entries. It does not state any analytic or RLCT invariance.
-/

noncomputable section

open Matrix

namespace DLNFibre
namespace DLN
namespace Aoyagi

section EntryIdeal

variable {R : Type*} [CommRing R]

/-- The ideal generated by all entries of a matrix. -/
def matrixEntryIdeal {m n : Type*} (A : Matrix m n R) : Ideal R :=
  Ideal.span (Set.range fun ij : m × n => A ij.1 ij.2)

/-- Every entry of a matrix lies in its matrix-entry ideal. -/
theorem matrixEntry_mem {m n : Type*} (A : Matrix m n R) (i : m) (j : n) :
    A i j ∈ matrixEntryIdeal A :=
  Ideal.subset_span ⟨(i, j), rfl⟩

/-- Stacking two row blocks generates the supremum of their matrix-entry ideals. -/
theorem matrixEntryIdeal_sumElim_eq_sup {m m' n : Type*}
    (A : Matrix m n R) (B : Matrix m' n R) :
    matrixEntryIdeal (Sum.elim A B) = matrixEntryIdeal A ⊔ matrixEntryIdeal B := by
  refine le_antisymm ?_ ?_
  · rw [matrixEntryIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    rcases i with i | i
    · exact (show matrixEntryIdeal A ≤ matrixEntryIdeal A ⊔ matrixEntryIdeal B from
        le_sup_left) (matrixEntry_mem A i j)
    · exact (show matrixEntryIdeal B ≤ matrixEntryIdeal A ⊔ matrixEntryIdeal B from
        le_sup_right) (matrixEntry_mem B i j)
  · refine sup_le ?_ ?_
    · rw [matrixEntryIdeal, Ideal.span_le]
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact matrixEntry_mem (Sum.elim A B) (Sum.inl i) j
    · rw [matrixEntryIdeal, Ideal.span_le]
      rintro _ ⟨⟨i, j⟩, rfl⟩
      exact matrixEntry_mem (Sum.elim A B) (Sum.inr i) j

/-- Replacing the lower row block by another matrix with the same entry ideal
preserves the entry ideal after stacking over a fixed top block. -/
theorem matrixEntryIdeal_sumElim_congr_bottom {m m' m'' n : Type*}
    (Top : Matrix m n R) {A : Matrix m' n R} {B : Matrix m'' n R}
    (h : matrixEntryIdeal A = matrixEntryIdeal B) :
    matrixEntryIdeal (Sum.elim Top A) = matrixEntryIdeal (Sum.elim Top B) := by
  rw [matrixEntryIdeal_sumElim_eq_sup, matrixEntryIdeal_sumElim_eq_sup, h]

/-- Adding a bottom block of zero rows does not change the matrix-entry ideal. -/
theorem matrixEntryIdeal_sumElim_zero_bottom {m m' n : Type*}
    (A : Matrix m n R) :
    matrixEntryIdeal (Sum.elim A (0 : Matrix m' n R)) = matrixEntryIdeal A := by
  refine le_antisymm ?_ ?_
  · rw [matrixEntryIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    rcases i with i | i
    · exact matrixEntry_mem A i j
    · simp
  · rw [matrixEntryIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    exact matrixEntry_mem (Sum.elim A (0 : Matrix m' n R)) (Sum.inl i) j

/-- Left multiplication can only decrease the matrix-entry ideal. -/
theorem matrixEntryIdeal_mul_left_le {l m n : Type*} [Fintype m]
    (P : Matrix l m R) (A : Matrix m n R) :
    matrixEntryIdeal (P * A) ≤ matrixEntryIdeal A := by
  rw [matrixEntryIdeal, Ideal.span_le]
  rintro _ ⟨⟨i, j⟩, rfl⟩
  change (P * A) i j ∈ matrixEntryIdeal A
  rw [Matrix.mul_apply]
  exact Ideal.sum_mem _ fun k _ ↦
    (matrixEntryIdeal A).mul_mem_left (P i k) (matrixEntry_mem A k j)

/-- Right multiplication can only decrease the matrix-entry ideal. -/
theorem matrixEntryIdeal_mul_right_le {m n p : Type*} [Fintype n]
    (A : Matrix m n R) (Q : Matrix n p R) :
    matrixEntryIdeal (A * Q) ≤ matrixEntryIdeal A := by
  rw [matrixEntryIdeal, Ideal.span_le]
  rintro _ ⟨⟨i, j⟩, rfl⟩
  change (A * Q) i j ∈ matrixEntryIdeal A
  rw [Matrix.mul_apply]
  exact Ideal.sum_mem _ fun k _ ↦
    (matrixEntryIdeal A).mul_mem_right (Q k j) (matrixEntry_mem A i k)

/-- Determinant-unit left multiplication preserves the matrix-entry ideal. -/
theorem matrixEntryIdeal_mul_left_eq_of_isUnit_det {m n : Type*}
    [Fintype m] [DecidableEq m] (P : Matrix m m R) (A : Matrix m n R)
    (hP : IsUnit P.det) :
    matrixEntryIdeal (P * A) = matrixEntryIdeal A := by
  refine le_antisymm (matrixEntryIdeal_mul_left_le P A) ?_
  have hcancel : P⁻¹ * (P * A) = A := by
    rw [← Matrix.mul_assoc, Matrix.nonsing_inv_mul P hP, Matrix.one_mul]
  calc
    matrixEntryIdeal A = matrixEntryIdeal (P⁻¹ * (P * A)) := by rw [hcancel]
    _ ≤ matrixEntryIdeal (P * A) := matrixEntryIdeal_mul_left_le P⁻¹ (P * A)

/-- The determinant-unit hypothesis for left multiplication is inhabited by the identity. -/
example {m n : Type*} [Fintype m] [DecidableEq m] (A : Matrix m n R) :
    matrixEntryIdeal ((1 : Matrix m m R) * A) = matrixEntryIdeal A :=
  matrixEntryIdeal_mul_left_eq_of_isUnit_det (1 : Matrix m m R) A (by simp)

/-- Determinant-unit right multiplication preserves the matrix-entry ideal. -/
theorem matrixEntryIdeal_mul_right_eq_of_isUnit_det {m n : Type*}
    [Fintype n] [DecidableEq n] (A : Matrix m n R) (Q : Matrix n n R)
    (hQ : IsUnit Q.det) :
    matrixEntryIdeal (A * Q) = matrixEntryIdeal A := by
  refine le_antisymm (matrixEntryIdeal_mul_right_le A Q) ?_
  have hcancel : (A * Q) * Q⁻¹ = A := by
    rw [Matrix.mul_assoc, Matrix.mul_nonsing_inv Q hQ, Matrix.mul_one]
  calc
    matrixEntryIdeal A = matrixEntryIdeal ((A * Q) * Q⁻¹) := by rw [hcancel]
    _ ≤ matrixEntryIdeal (A * Q) := matrixEntryIdeal_mul_right_le (A * Q) Q⁻¹

/-- The determinant-unit hypothesis for right multiplication is inhabited by the identity. -/
example {m n : Type*} [Fintype n] [DecidableEq n] (A : Matrix m n R) :
    matrixEntryIdeal (A * (1 : Matrix n n R)) = matrixEntryIdeal A :=
  matrixEntryIdeal_mul_right_eq_of_isUnit_det A (1 : Matrix n n R) (by simp)

/-- Entries of a product are generated by the entries of the two factors. -/
theorem matrixEntryIdeal_mul_le_sup {m n p : Type*} [Fintype n]
    (A : Matrix m n R) (B : Matrix n p R) :
    matrixEntryIdeal (A * B) ≤ matrixEntryIdeal A ⊔ matrixEntryIdeal B := by
  rw [matrixEntryIdeal, Ideal.span_le]
  rintro _ ⟨⟨i, j⟩, rfl⟩
  change (A * B) i j ∈ matrixEntryIdeal A ⊔ matrixEntryIdeal B
  rw [Matrix.mul_apply]
  exact Ideal.sum_mem _ fun k _ ↦
    (matrixEntryIdeal A ⊔ matrixEntryIdeal B).mul_mem_right (B k j) <|
      (show matrixEntryIdeal A ≤ matrixEntryIdeal A ⊔ matrixEntryIdeal B from le_sup_left)
        (matrixEntry_mem A i k)

/-- The ideal generated by four matrix-entry families, used after Aoyagi's Theorem 3. -/
def fourMatrixEntryIdeal {a b m n p : Type*}
    (X : Matrix a b R) (F2 : Matrix n p R) (F3 : Matrix m n R)
    (D : Matrix m p R) : Ideal R :=
  ((matrixEntryIdeal X ⊔ matrixEntryIdeal F2) ⊔ matrixEntryIdeal F3) ⊔ matrixEntryIdeal D

/-- The term `F3 * F2` is redundant once the entries of `F2` and `F3` are generators. -/
theorem fourMatrixEntryIdeal_sub_mul_eq {a b m n p : Type*} [Fintype n]
    (X : Matrix a b R) (F2 : Matrix n p R) (F3 : Matrix m n R)
    (D : Matrix m p R) :
    fourMatrixEntryIdeal X F2 F3 (D - F3 * F2) =
      fourMatrixEntryIdeal X F2 F3 D := by
  let base : Ideal R := (matrixEntryIdeal X ⊔ matrixEntryIdeal F2) ⊔ matrixEntryIdeal F3
  have hF2_le_base : matrixEntryIdeal F2 ≤ base :=
    le_trans le_sup_right le_sup_left
  have hF3_le_base : matrixEntryIdeal F3 ≤ base :=
    le_sup_right
  have hmul_le_base : matrixEntryIdeal (F3 * F2) ≤ base :=
    (matrixEntryIdeal_mul_le_sup F3 F2).trans (sup_le hF3_le_base hF2_le_base)
  unfold fourMatrixEntryIdeal
  change base ⊔ matrixEntryIdeal (D - F3 * F2) = base ⊔ matrixEntryIdeal D
  refine le_antisymm ?_ ?_
  · refine sup_le le_sup_left ?_
    rw [matrixEntryIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    change (D - F3 * F2) i j ∈ base ⊔ matrixEntryIdeal D
    have hD : D i j ∈ base ⊔ matrixEntryIdeal D :=
      (show matrixEntryIdeal D ≤ base ⊔ matrixEntryIdeal D from le_sup_right)
        (matrixEntry_mem D i j)
    have hprod : (F3 * F2) i j ∈ base ⊔ matrixEntryIdeal D :=
      (show base ≤ base ⊔ matrixEntryIdeal D from le_sup_left)
        (hmul_le_base (matrixEntry_mem (F3 * F2) i j))
    exact (base ⊔ matrixEntryIdeal D).sub_mem hD hprod
  · refine sup_le le_sup_left ?_
    rw [matrixEntryIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    change D i j ∈ base ⊔ matrixEntryIdeal (D - F3 * F2)
    have hsub : (D - F3 * F2) i j ∈ base ⊔ matrixEntryIdeal (D - F3 * F2) :=
      (show matrixEntryIdeal (D - F3 * F2) ≤ base ⊔ matrixEntryIdeal (D - F3 * F2) from
        le_sup_right) (matrixEntry_mem (D - F3 * F2) i j)
    have hprod : (F3 * F2) i j ∈ base ⊔ matrixEntryIdeal (D - F3 * F2) :=
      (show base ≤ base ⊔ matrixEntryIdeal (D - F3 * F2) from le_sup_left)
        (hmul_le_base (matrixEntry_mem (F3 * F2) i j))
    have hsum := (base ⊔ matrixEntryIdeal (D - F3 * F2)).add_mem hsub hprod
    simpa [Pi.sub_apply] using hsum

end EntryIdeal

end Aoyagi
end DLN
end DLNFibre
