#!/usr/bin/env python3
# provenance: threads/L4-case1-core (SEAT-L4). Fork-(A) consistency datum for the elder's ruling —
# does the REAL construction shear make fork-(A) preservation mechanical? (demoted from hypothesis-
# candidate to CONSISTENCY DATUM; feeds the round's gate as corroboration.)
"""
FORK (A) = carry the invariant on the STRICT-TRANSFORMED residual over T, with IDEAL-MEMBERSHIP
coefficients (resid ∈ ⟨T-coords⟩), born-pivot content as the right disjunct (unit-form).

We confirm, EXACTLY (sympy/ℚ), against the REAL construction shear from thread-33's shear-pin
(the Schur reduction, the ONLY shear that enters g; Q1 is the witness cofactor, off g):

  (S) PIVOT-INDEPENDENCE: the real shear φ neither reads nor writes the pivot (exceptional) coord.
      φ = the Schur map C22 ↦ C22 − C21·C12 on the residual block; pivot = the normalized c11.
      ⟹ hshear_pivot holds, AND (unlike seat-L3T's countermodel sh(u_p,u_i)=(u_p,u_i+u_p)) the real
      shear never reads u_pivot. The distinguishing property is PIVOT-INDEPENDENCE, not "T-untouched"
      (the Schur shear genuinely mixes WITHIN T).

  (A1) IDEAL-MEMBERSHIP IS CLOSED under the real shear + strict transform: for every T-coordinate i,
       the strict-transform coordinate blockBlowupCoordQuot(pivot,i)∘(shear) ∈ ⟨T⟩. Hence a parent
       residual that is ideal-degree-1 over T pulls back to a child that is again ideal-degree-1 over T
       (left disjunct) — conjunct-B is MECHANICAL in the ideal-membership form.

  (A2) THE PIVOT SLOT → UNIT (right disjunct): blockBlowupCoordQuot(pivot,pivot) = 1, so the cleared-
       pivot residual slot is the born-terminally unit — the LastLayerInv right disjunct exemplar.

  (X) CRUX-FIT CONSTRAINT (the load-bearing rendering datum): center-exact Deg1 (IgnoresCoords) is
      NOT closed under the real Schur shear (the C21·C12 term is degree-2), whereas ideal-membership
      IS. So fork-(A)'s left disjunct is correctly ideal-membership. BUT the banked crux
      foldResid_stepMap_eq_pivot_mul consumes IgnoresCoords (center-DISJOINT coefficients) in its
      hceq step — strictly stronger than ideal-membership. We exhibit both facts so the round renders
      LastLayerInv's left disjunct crux-ready (coefficients center-disjoint in the PREPARED frame,
      which the Let-block rename supplies — not bare ideal-membership in the raw frame).
"""
import sys
import sympy as sp

ok = True
def check(name, cond):
    global ok
    ok &= bool(cond)
    print(f"  [{'PASS' if cond else 'FAIL'}] {name}")

# --- the real Schur shear on the (3,3,4) residual block (thread-33 shear_roles.py) ---
# center block coords: pivot c11 (normalized), T = {C12=(c12a,c12b), C21=(c21a,c21b), C22=(m11..m22)}.
c11 = sp.Symbol('c11')
c12a, c12b, c21a, c21b = sp.symbols('c12a c12b c21a c21b')
m11, m12, m21, m22 = sp.symbols('m11 m12 m21 m22')
pivot = c11
T = [c12a, c12b, c21a, c21b, m11, m12, m21, m22]        # center ∖ {pivot}
C12 = sp.Matrix([[c12a, c12b]]); C21 = sp.Matrix([[c21a], [c21b]])
C22 = sp.Matrix([[m11, m12], [m21, m22]])
Delta = C22 - C21 * C12                                  # Schur complement

# the real shear as a self-map of the block coords (thread-33: keep C12,C21,pivot; C22 ↦ Δ):
shear = {m11: Delta[0, 0], m12: Delta[0, 1], m21: Delta[1, 0], m22: Delta[1, 1]}
# (c11, c12a, c12b, c21a, c21b unchanged — kept)

# (S) pivot-independence: the shear does not read the pivot, and fixes the pivot.
reads_pivot = any(pivot in sp.expand(v).free_symbols for v in shear.values())
fixes_pivot = pivot not in shear                         # c11 not remapped ⟹ φ_pivot = 0
check("(S) real shear is PIVOT-INDEPENDENT: never reads u_pivot", not reads_pivot)
check("(S) real shear FIXES the pivot (hshear_pivot): c11 ↦ c11", fixes_pivot)

# contrast: the seat-L3T countermodel READS the pivot (would break pivot-independence)
cm_reads_pivot = pivot in sp.expand(m11 + pivot).free_symbols   # sh: m11 ↦ m11 + c11
check("(S) countermodel sh(m11)=m11+u_pivot READS the pivot (excluded by pivot-independence)",
      cm_reads_pivot)

# --- strict-transform coordinate: blockBlowupCoordQuot(pivot,i)∘shear ---
def quot_after_shear(i):
    """blockBlowupCoordQuot pivot i (shear u): 1 if i==pivot else (shear u)_i."""
    if i == pivot:
        return sp.Integer(1)
    return sp.expand(sp.Symbol(str(i)).subs(shear)) if sp.Symbol(str(i)) in shear else i

Tideal = sp.groebner([sp.expand(x) for x in T], *([pivot] + T), order='lex')
def in_T_ideal(expr):
    """is expr ∈ ⟨T⟩ ? (reduce mod the ideal generated by the T-coordinates)."""
    return sp.expand(Tideal.reduce(sp.expand(expr))[1]) == 0

# (A1) ideal-membership closed: every T strict-transform coord ∈ ⟨T⟩
a1 = all(in_T_ideal(quot_after_shear(i)) for i in T)
check("(A1) ideal-membership CLOSED: each T strict-transform coord ∈ ⟨T⟩ (child ideal-degree-1)", a1)

# (A2) pivot slot → unit (right disjunct)
a2 = quot_after_shear(pivot) == 1
check("(A2) pivot slot strict-transform = 1 (born-terminally unit = right disjunct)", a2)

# (X) crux-fit: center-exact Deg1 is NOT closed (C22 slot picks up the degree-2 C21·C12);
#     ideal-membership IS. So left disjunct = ideal-membership; crux needs the disjoint (prepared) form.
c22_strict = quot_after_shear(m11)                       # = m11 - c21a*c12a  (degree 2 in T)
poly = sp.Poly(c22_strict, *T)
maxdeg = max(sum(mono) for mono in poly.monoms())
check("(X) C22 strict-transform is DEGREE-2 in T (center-exact Deg1 NOT closed; ideal-membership IS)",
      maxdeg == 2 and in_T_ideal(c22_strict))

print(f"\nfork-(A) consistency datum: {'PASS' if ok else 'FAIL'}")
print("SUMMARY: real shear pivot-independent + Schur-within-T; ideal-membership closed under it")
print("  (conjunct-B mechanical in fork-A form); pivot slot → unit (right disjunct). CRUX-FIT: the")
print("  banked crux needs center-DISJOINT coefficients (IgnoresCoords) — render LastLayerInv's left")
print("  disjunct in the PREPARED frame (Let-block rename ⟹ disjoint), not bare raw ideal-membership.")
sys.exit(0 if ok else 1)
