import DLNFibre.Core.AffineNoetherRank
import DLNFibre.Core.JacobianTrdeg
import DLNFibre.Core.OrbitCodim

/-!
# `DLNFibre.Core.OrbitImageDim` — A4.4: the route-c submersion bound (assembly)

The headline of the L2b★ route-c chain that, combined with the landed A0
(`varietyDim_eq_ringKrullDim_range_orbitPullback`), discharges the AG-half of `hVoigt`:

> `(ringKrullDim (orbitPullback M).range).unbotD 0 ≤ finrank k (LinearMap.range (deformationδ M M))`.

The chain (A0 landed, A4.1 landed, A4.2/A4.3 the named open obligations):
- **A0** (landed): `varietyDim Z_M = (ringKrullDim (orbitPullback M).range).unbotD 0`.
- **A4.1** (landed, `ringKrullDim_range_orbitPullback_unbotD_eq_trdeg_toNat`):
  `(ringKrullDim (orbitPullback M).range).unbotD 0 = (Algebra.trdeg k (orbitPullback M).range).toNat`.
- **A4.2** (the char-0 differential criterion, `genericDifferentialRank` the shared rank object;
  the open obligation is `DiffIndepCriterion`, with the routine trdeg reduction folded into the
  `hA42` hypothesis below): `(Algebra.trdeg k (orbitPullback M).range).toNat ≤
  genericDifferentialRank k (groupRing d) (genericOrbitCoord M)`.
- **A4.3** (the char-free differential-rank identity, the orbit-map differential = `δ⁰`; the open
  obligation `hA43`): `genericDifferentialRank k (groupRing d) (genericOrbitCoord M) =
  finrank k (LinearMap.range (deformationδ M M))`.

This module assembles A4.4 from A4.1 (proved) and the two named hypotheses `hA42`, `hA43`. The two
hypotheses are the residual open obligations of the route — stated at exact precision so a focused
follow-up can discharge each independently. `[CharZero k]` is carried on `hA42`'s side (the criterion
is char-0); the assembly itself is char-free.

**Dependency rule:** `Core` only — never import `DLNFibre.DLN`.
-/

namespace DLNFibre.Core

open MvPolynomial Algebra Module

universe u

variable {k : Type u} [Field k] {N : ℕ}

/-- The pullback image `(orbitPullback M).range` is generated by the orbit coordinates:
`(orbitPullback M).range = Algebra.adjoin k (Set.range (genericOrbitCoord M))` — the range of an
`aeval` is the subalgebra generated by the evaluation family (`MvPolynomial.aeval_range`). -/
theorem range_orbitPullback_eq_adjoin {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    (orbitPullback M).range = Algebra.adjoin k (Set.range (genericOrbitCoord M)) := by
  rw [orbitPullback, MvPolynomial.aeval_range]

/-- **A4.4: the route-c submersion bound (assembly).** The Krull dimension of the orbit-pullback
image is at most the dimension of the image of the deformation differential `δ⁰ = deformationδ M M`:

> `(ringKrullDim (orbitPullback M).range).unbotD 0 ≤ finrank k (LinearMap.range (deformationδ M M))`.

Proved from A4.1 (`= trdeg`, landed) and the two named obligations: `hA42`, the char-0 differential
criterion in image-form (`trdeg ≤ genericDifferentialRank`), and `hA43`, the char-free
differential-rank identity (`genericDifferentialRank = finrank (range δ⁰)`). `[CharZero k]` is the
hypothesis under which `hA42` holds; the assembly here uses only `[Field k]`. -/
theorem ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ
    {d : Fin (N + 1) → ℕ} [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hA42 : (Algebra.trdeg k (orbitPullback M).range).toNat
      ≤ genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M))
    (hA43 : genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M)
      = finrank k (LinearMap.range (deformationδ M M))) :
    (ringKrullDim (orbitPullback M).range).unbotD 0
      ≤ finrank k (LinearMap.range (deformationδ M M)) := by
  rw [ringKrullDim_range_orbitPullback_unbotD_eq_trdeg_toNat M]
  exact_mod_cast hA42.trans (le_of_eq hA43)

/-- **A4.4 chained with A0: `varietyDim Z_M ≤ finrank (range δ⁰)`.** Combining the landed A0 link
(`varietyDim_eq_ringKrullDim_range_orbitPullback`, needs `[Infinite k]`) with the submersion bound,
the variety dimension of the determinantal rank locus `Z_M` is at most the dimension of the orbit
tangent image — the AG-half submersion inequality of `hVoigt`. Conditional on the same two named
obligations `hA42`, `hA43`. -/
theorem varietyDim_orbitRankLocus_le_finrank_range_deformationδ
    [Infinite k] {d : Fin (N + 1) → ℕ} [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hA42 : (Algebra.trdeg k (orbitPullback M).range).toNat
      ≤ genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M))
    (hA43 : genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M)
      = finrank k (LinearMap.range (deformationδ M M))) :
    varietyDim (canonicalCoord d '' orbitRankLocus M)
      ≤ finrank k (LinearMap.range (deformationδ M M)) := by
  rw [varietyDim_eq_ringKrullDim_range_orbitPullback M]
  exact ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ M hA42 hA43

end DLNFibre.Core
