import DLNFibre.Core.AffineNoetherRank
import DLNFibre.Core.JacobianTrdeg
import DLNFibre.Core.OrbitCodim
import Mathlib.RingTheory.EssentialFiniteness

/-!
# `DLNFibre.Core.OrbitImageDim` — A4.4: the route-c submersion bound (assembly)

The headline of the L2b★ route-c chain that, combined with the landed A0
(`varietyDim_eq_ringKrullDim_range_orbitPullback`), discharges the AG-half of `hVoigt`:

> `(ringKrullDim (orbitPullback M).range).unbotD 0 ≤ finrank k (LinearMap.range (deformationδ M M))`.

The chain (A0 landed, A4.1 landed, A4.2/A4.3 the named open obligations):
- **A0** (landed): `varietyDim Z_M = (ringKrullDim (orbitPullback M).range).unbotD 0`.
- **A4.1** (landed, `ringKrullDim_range_orbitPullback_unbotD_eq_trdeg_toNat`):
  `(ringKrullDim (orbitPullback M).range).unbotD 0 = (Algebra.trdeg k (orbitPullback M).range).toNat`.
- **A4.2** (the char-0 differential criterion, `genericDifferentialRank` the shared rank object;
  the open obligation is `DiffIndepCriterion`, with the routine trdeg reduction folded into the
  `hA42` hypothesis below): `(Algebra.trdeg k (orbitPullback M).range).toNat ≤
  genericDifferentialRank k (groupRing d) (genericOrbitCoord M)`.
- **A4.3** (the char-free differential-rank identity, the orbit-map differential = `δ⁰`; the open
  obligation `hA43`): `genericDifferentialRank k (groupRing d) (genericOrbitCoord M) =
  finrank k (LinearMap.range (deformationδ M M))`.

This module assembles A4.4 from A4.1 (proved) and the two named hypotheses `hA42`, `hA43`. The two
hypotheses are the residual open obligations of the route — stated at exact precision so a focused
follow-up can discharge each independently. `[CharZero k]` is carried on `hA42`'s side (the criterion
is char-0); the assembly itself is char-free.

**Dependency rule:** `Core` only — never import `DLNFibre.DLN`.
-/

namespace DLNFibre.Core

open MvPolynomial Algebra Module

universe u

variable {k : Type u} [Field k] {N : ℕ}

/-- **`groupRing d` is essentially of finite type over `k`.** A localization
(`Localization.Away (groupDenom d)`) of the finite-type `MvPolynomial (GroupCoord d) k`, composed
through `EssFiniteType`. This discharges the `EssFiniteType` side-condition that
`Algebra.FormallySmooth.of_perfectField` needs for the A4.2 criterion `DiffIndepCriterion` over the
fraction field of `groupRing d` (see the thread statement card). -/
instance essFiniteType_groupRing {d : Fin (N + 1) → ℕ} :
    Algebra.EssFiniteType k (groupRing (k := k) d) := by
  haveI : Algebra.EssFiniteType (MvPolynomial (GroupCoord d) k) (groupRing (k := k) d) :=
    Algebra.EssFiniteType.of_isLocalization _ (Submonoid.powers (groupDenom (k := k) d))
  exact Algebra.EssFiniteType.comp k (MvPolynomial (GroupCoord d) k) (groupRing (k := k) d)

/-- **The fraction field of `groupRing d` is essentially of finite type over `k`.** One more
localization (`nonZeroDivisors`) on top of `essFiniteType_groupRing`. This is the hypothesis the A4.2
criterion's formal-smoothness step (`FormallySmooth.of_perfectField`) consumes. -/
instance essFiniteType_fractionRing_groupRing {d : Fin (N + 1) → ℕ} :
    Algebra.EssFiniteType k (FractionRing (groupRing (k := k) d)) := by
  haveI : Algebra.EssFiniteType (groupRing (k := k) d) (FractionRing (groupRing (k := k) d)) :=
    Algebra.EssFiniteType.of_isLocalization _ (nonZeroDivisors (groupRing (k := k) d))
  exact Algebra.EssFiniteType.comp k (groupRing (k := k) d) (FractionRing (groupRing (k := k) d))

/-- The pullback image `(orbitPullback M).range` is generated by the orbit coordinates:
`(orbitPullback M).range = Algebra.adjoin k (Set.range (genericOrbitCoord M))` — the range of an
`aeval` is the subalgebra generated by the evaluation family (`MvPolynomial.aeval_range`). -/
theorem range_orbitPullback_eq_adjoin {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    (orbitPullback M).range = Algebra.adjoin k (Set.range (genericOrbitCoord M)) := by
  rw [orbitPullback, MvPolynomial.aeval_range]

/-- **A4.4: the route-c submersion bound (assembly).** The Krull dimension of the orbit-pullback
image is at most the dimension of the image of the deformation differential `δ⁰ = deformationδ M M`:

> `(ringKrullDim (orbitPullback M).range).unbotD 0 ≤ finrank k (LinearMap.range (deformationδ M M))`.

Proved from A4.1 (`= trdeg`, landed) and the two named obligations: `hA42`, the char-0 differential
criterion in image-form (`trdeg ≤ genericDifferentialRank`), and `hA43_le`, the char-free
differential-rank bound (`genericDifferentialRank ≤ finrank (range δ⁰)`). Only the `≤` direction of
the A4.3 identity is needed (the chain is `varietyDim = trdeg ≤ genericDifferentialRank ≤ finrank δ⁰`);
the assembly here uses only `[Field k]`. -/
theorem ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ
    {d : Fin (N + 1) → ℕ} [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hA42 : (Algebra.trdeg k (orbitPullback M).range).toNat
      ≤ genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M))
    (hA43_le : genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M)
      ≤ finrank k (LinearMap.range (deformationδ M M))) :
    (ringKrullDim (orbitPullback M).range).unbotD 0
      ≤ finrank k (LinearMap.range (deformationδ M M)) := by
  rw [ringKrullDim_range_orbitPullback_unbotD_eq_trdeg_toNat M]
  exact_mod_cast hA42.trans hA43_le

/-- **A4.4 chained with A0: `varietyDim Z_M ≤ finrank (range δ⁰)`.** Combining the landed A0 link
(`varietyDim_eq_ringKrullDim_range_orbitPullback`, needs `[Infinite k]`) with the submersion bound,
the variety dimension of the determinantal rank locus `Z_M` is at most the dimension of the orbit
tangent image — the AG-half submersion inequality of `hVoigt`. Conditional on `hA42` and the `≤`-form
A4.3 bound `hA43_le`. -/
theorem varietyDim_orbitRankLocus_le_finrank_range_deformationδ
    [Infinite k] {d : Fin (N + 1) → ℕ} [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hA42 : (Algebra.trdeg k (orbitPullback M).range).toNat
      ≤ genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M))
    (hA43_le : genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M)
      ≤ finrank k (LinearMap.range (deformationδ M M))) :
    varietyDim (canonicalCoord d '' orbitRankLocus M)
      ≤ finrank k (LinearMap.range (deformationδ M M)) := by
  rw [varietyDim_eq_ringKrullDim_range_orbitPullback M]
  exact ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ M hA42 hA43_le

/-! ## Reducing `hA42` to the clean char-0 criterion `DiffIndepCriterion`

`hA42` (the image-form A4.2 bound) follows from the field-theory criterion `DiffIndepCriterion k
(groupRing d)` via the trdeg wrapper, since `(orbitPullback M).range = adjoin k (range
(genericOrbitCoord M))`. This pins the genuine open obligation of A4.2 to `DiffIndepCriterion` —
the char-0 "algebraically-independent ⟹ differentials linearly independent" fact — separated from
all the orbit-specific bookkeeping. -/

-- `genericDifferentialRank` over the localization `groupRing d` is costly to unfold during
-- unification; the default heartbeat budget is exceeded by the `range_orbitPullback_eq_adjoin`
-- rewrite, so bump it for this single bridging lemma.
set_option maxHeartbeats 800000 in
/-- **A4.2 image-form from the criterion.** `(Algebra.trdeg k (orbitPullback M).range).toNat ≤
genericDifferentialRank …` from `DiffIndepCriterion k (groupRing d)`: the trdeg wrapper applied to
`f = genericOrbitCoord M`, with `(orbitPullback M).range = adjoin k (range (genericOrbitCoord M))`
(`range_orbitPullback_eq_adjoin`). -/
theorem trdeg_range_orbitPullback_le_genericDifferentialRank {d : Fin (N + 1) → ℕ}
    [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hcrit : DiffIndepCriterion k (groupRing (k := k) d)) :
    (Algebra.trdeg k (orbitPullback M).range).toNat
      ≤ genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M) := by
  have h := trdeg_adjoin_le_genericDifferentialRank k (groupRing (k := k) d)
    (genericOrbitCoord M) hcrit
  rwa [← range_orbitPullback_eq_adjoin M] at h

/-- **A4.4 from the criterion + A4.3.** The route-c submersion bound with the A4.2 obligation
discharged down to the clean char-0 criterion `DiffIndepCriterion k (groupRing d)`; `hA43_le` remains
the char-free differential-rank bound (the A4.3 `≤`-obligation). -/
theorem ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ_of_criterion
    {d : Fin (N + 1) → ℕ} [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hcrit : DiffIndepCriterion k (groupRing (k := k) d))
    (hA43_le : genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M)
      ≤ finrank k (LinearMap.range (deformationδ M M))) :
    (ringKrullDim (orbitPullback M).range).unbotD 0
      ≤ finrank k (LinearMap.range (deformationδ M M)) :=
  ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ M
    (trdeg_range_orbitPullback_le_genericDifferentialRank M hcrit) hA43_le

/-- **A4.2 criterion discharged for `groupRing d`** (char 0). `DiffIndepCriterion k (groupRing d)`
holds by `diffIndepCriterion_proof`, using the landed `essFiniteType_fractionRing_groupRing` instance
for the `EssFiniteType k (FractionRing (groupRing d))` side-condition. -/
theorem diffIndepCriterion_groupRing [CharZero k] {d : Fin (N + 1) → ℕ} :
    DiffIndepCriterion k (groupRing (k := k) d) :=
  diffIndepCriterion_proof k (groupRing (k := k) d)

/-- **A4.4 in char 0, A4.2 fully discharged.** The route-c submersion bound with NO criterion
hypothesis — `DiffIndepCriterion` is now `diffIndepCriterion_groupRing`; only `hA43_le` (the char-free
A4.3 differential-rank `≤`-bound) remains. -/
theorem ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ_charZero
    [CharZero k] {d : Fin (N + 1) → ℕ} [Fintype (RepCoord d)] (M : Tuple (k := k) d)
    (hA43_le : genericDifferentialRank k (groupRing (k := k) d) (genericOrbitCoord M)
      ≤ finrank k (LinearMap.range (deformationδ M M))) :
    (ringKrullDim (orbitPullback M).range).unbotD 0
      ≤ finrank k (LinearMap.range (deformationδ M M)) :=
  ringKrullDim_range_orbitPullback_le_finrank_range_deformationδ_of_criterion M
    diffIndepCriterion_groupRing hA43_le

end DLNFibre.Core
