import DLNFibre.Core.OrbitVariety
import DLNFibre.Core.Orbit
import DLNFibre.Core.GenericTuple
import DLNFibre.Core.Matrix.RankMinors

/-!
# `DLNFibre.Core.RankLocusClosed` — the rank locus is Zariski-closed (L6.3, easy direction)

The Zariski-closedness of `orbitRankLocus M ⊆ Rep_d` — the determinantal locus cut out by the
rank conditions `rankPattern A ≤ rankPattern M` (Lehalleur–Rimányi 2024 Thm 3.8 says this set *is*
the orbit closure `Ō_M`; that identification is L6.1/L6.2, NOT here). This module proves the
**topological** content of the easy inclusion `Ō_M ⊆ orbitRankLocus M`: the rank locus is closed,
so the closure of the orbit `O_M` stays inside it once `O_M ⊆ orbitRankLocus M`. Two pieces:

1. **The determinantal-rank criterion** (`Matrix.rank_le_iff_forall_submatrix_det_eq_zero`, now in
   the network-free Core library `DLNFibre.Core.Matrix.RankMinors`): over a field, `A.rank ≤ r` iff
   every `(r+1)×(r+1)` submatrix of `A` has determinant `0`.
2. **Closedness** (`isZariskiClosed_orbitRankLocus`): the entries of `submult d A i j` are
   polynomials in the matrix entries (the **generic tuple** `genericTuple`, entries = coordinate
   variables, evaluated at `canonicalCoord A`), so each `(r+1)`-minor is a polynomial `minorPoly`.
   The criterion writes `canonicalCoord '' orbitRankLocus M` as the `zeroLocus` of the ideal
   generated by the minor polynomials, and a `zeroLocus` is Zariski-closed (Galois-connection
   `l_u_l_eq_l`).

Plus the easy orbit inclusion `O_M ⊆ orbitRankLocus M` (`orbitSet_subset_orbitRankLocus`,
`rankPattern`-invariance, `rankPattern_eq_iff_orbit`) and the resulting ideal inclusion. No field
algebraic-closedness is needed for closedness; `[Field k]` suffices.

**Dependency rule:** `Core` only — never import `DLNFibre.DLN`.
-/

namespace DLNFibre.Core

open Matrix MvPolynomial Submodule Module

universe u

variable {k : Type u} [Field k]

/-! ## Polynomialization: the rank-pattern minors as coordinate polynomials

The entries of `submult d A i j` are polynomials in the matrix entries of `A`. We realise this with
the **generic tuple** `genericTuple d`, the tuple over the coordinate ring whose `(i, r, c)` entry
is the variable `X ⟨i, r, c⟩`; evaluating at the point `canonicalCoord d A` recovers `A`. Then
`submult` of the generic tuple, evaluated, is `submult` of `A` (matrix multiplication commutes with
the ring hom `eval`), and each `(s)`-minor of the generic `submult` is a polynomial whose value at
`canonicalCoord d A` is the corresponding numerical minor of `submult d A i j`. -/

variable {N : ℕ}

-- `genericTuple` and `eval_genericTuple` now live in `Core.GenericTuple` (over any `CommRing`, the
-- weakest hypothesis), reused here and by `Core.MultComorphism`.

/-- Evaluating the generic interval sub-product at `canonicalCoord d A` recovers `submult d A i j`:
matrix multiplication commutes with the ring hom `eval`, and the generic factors evaluate to the
factors of `A` (`eval_genericTuple`). By induction on the upper index through `submult_succ`. -/
theorem eval_submult_genericTuple {d : Fin (N + 1) → ℕ} (A : Tuple (k := k) d)
    (i j : Fin (N + 1)) (hij : i ≤ j) :
    (submult d (genericTuple (k := k) d) i j hij).map (MvPolynomial.eval (canonicalCoord d A))
      = submult d A i j hij := by
  induction j using Fin.induction with
  | zero =>
    obtain rfl : i = 0 := le_antisymm hij (Fin.zero_le i)
    rw [submult_self, submult_self, Matrix.map_one _ (map_zero _) (map_one _)]
  | succ p ih =>
    rcases eq_or_lt_of_le hij with heq | hlt
    · subst heq
      rw [submult_self, submult_self, Matrix.map_one _ (map_zero _) (map_one _)]
    · have hip : i ≤ p.castSucc := by
        rw [Fin.le_castSucc_iff]; exact hlt
      rw [submult_succ d (genericTuple (k := k) d) i p hip, submult_succ d A i p hip,
        Matrix.map_mul, eval_genericTuple A p, ih hip]

/-- The **minor polynomial**: the determinant of an `(s)×(s)` submatrix of the generic interval
sub-product `submult d (genericTuple d) i j`, a polynomial in the coordinate ring. Its value at
`canonicalCoord d A` is the corresponding numerical minor of `submult d A i j`
(`eval_minorPoly`). -/
noncomputable def minorPoly {d : Fin (N + 1) → ℕ} (i j : Fin (N + 1)) (hij : i ≤ j) {s : ℕ}
    (er : Fin s → Fin (d j)) (ec : Fin s → Fin (d i)) : MvPolynomial (RepCoord d) k :=
  ((submult d (genericTuple (k := k) d) i j hij).submatrix er ec).det

/-- Evaluating `minorPoly` at the point `canonicalCoord d A` yields the numerical `(s)`-minor of
`submult d A i j`: determinant commutes with the ring hom `eval` (`RingHom.map_det`), evaluation
commutes with `submatrix` (`Matrix.submatrix_map`), and the generic sub-product evaluates to
`submult d A i j` (`eval_submult_genericTuple`). -/
theorem eval_minorPoly {d : Fin (N + 1) → ℕ} (A : Tuple (k := k) d) (i j : Fin (N + 1))
    (hij : i ≤ j) {s : ℕ} (er : Fin s → Fin (d j)) (ec : Fin s → Fin (d i)) :
    MvPolynomial.eval (canonicalCoord d A) (minorPoly i j hij er ec)
      = ((submult d A i j hij).submatrix er ec).det := by
  rw [minorPoly, RingHom.map_det, RingHom.mapMatrix_apply, ← Matrix.submatrix_map,
    eval_submult_genericTuple A i j hij]

/-! ## The rank locus is Zariski-closed -/

/-- The set of **defining minor polynomials** of `orbitRankLocus M`: for each `(i, j)` with `i ≤ j`
and each pair of index maps `er, ec` of size `rankPattern M i j hij + 1`, the minor polynomial
`minorPoly i j hij er ec`. Its common zero locus is exactly `canonicalCoord '' orbitRankLocus M`. -/
def rankMinorSet {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    Set (MvPolynomial (RepCoord d) k) :=
  {p | ∃ (i j : Fin (N + 1)) (hij : i ≤ j)
      (er : Fin (rankPattern d M i j hij + 1) → Fin (d j))
      (ec : Fin (rankPattern d M i j hij + 1) → Fin (d i)), p = minorPoly i j hij er ec}

/-- A point `x` is a common zero of `rankMinorSet M` iff the tuple `A = canonicalCoord.symm x`
satisfies every rank bound `rankPattern A i j ≤ rankPattern M i j` — by the determinantal-rank
bridge applied to `submult d A i j`. -/
theorem mem_zeroLocus_rankMinorSet_iff {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d)
    (x : RepCoord d → k) :
    (∀ p ∈ rankMinorSet M, MvPolynomial.eval x p = 0) ↔
      (canonicalCoord d).symm x ∈ orbitRankLocus M := by
  set A := (canonicalCoord d).symm x with hA
  have hxA : x = canonicalCoord d A := by rw [hA, Equiv.apply_symm_apply]
  rw [orbitRankLocus, Set.mem_setOf_eq]
  constructor
  · -- common zero ⟹ all rank bounds hold
    intro hzero i j hij
    rw [show rankPattern d A i j hij = (submult d A i j hij).rank from rfl,
      rank_le_iff_forall_submatrix_det_eq_zero (submult d A i j hij)]
    intro er ec
    have hmem : minorPoly i j hij er ec ∈ rankMinorSet M := ⟨i, j, hij, er, ec, rfl⟩
    have := hzero _ hmem
    rw [hxA, eval_minorPoly A i j hij er ec] at this
    exact this
  · -- all rank bounds hold ⟹ common zero
    intro hrank p hp
    obtain ⟨i, j, hij, er, ec, rfl⟩ := hp
    rw [hxA, eval_minorPoly A i j hij er ec]
    have hle : (submult d A i j hij).rank ≤ rankPattern d M i j hij := hrank i j hij
    rw [rank_le_iff_forall_submatrix_det_eq_zero (submult d A i j hij)] at hle
    exact hle er ec

/-- `canonicalCoord '' orbitRankLocus M` is the zero locus of the minor ideal `span (rankMinorSet
M)`: it is cut out by the defining minor polynomials. -/
theorem image_orbitRankLocus_eq_zeroLocus {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    canonicalCoord d '' orbitRankLocus M
      = MvPolynomial.zeroLocus k (Ideal.span (rankMinorSet M)) := by
  rw [MvPolynomial.zeroLocus_span]
  ext x
  rw [Set.mem_setOf_eq]
  have heval : (∀ p ∈ rankMinorSet M, (MvPolynomial.aeval x) p = 0)
      ↔ (∀ p ∈ rankMinorSet M, MvPolynomial.eval x p = 0) := by
    simp only [MvPolynomial.aeval_eq_eval]
  rw [heval, mem_zeroLocus_rankMinorSet_iff M x]
  constructor
  · rintro ⟨A, hA, rfl⟩; rwa [Equiv.symm_apply_apply]
  · intro hx; exact ⟨(canonicalCoord d).symm x, hx, (canonicalCoord d).apply_symm_apply x⟩

/-- **The rank locus is Zariski-closed (L6.3).** `canonicalCoord '' orbitRankLocus M` equals the
zero locus of its own vanishing ideal — it is cut out by the determinantal minor polynomials
(`image_orbitRankLocus_eq_zeroLocus`), and any zero locus is Zariski-closed (the Galois-connection
fact `zeroLocus (vanishingIdeal (zeroLocus I)) = zeroLocus I`). This is the topological content of
the easy orbit-closure inclusion `Ō_M ⊆ orbitRankLocus M`. -/
theorem isZariskiClosed_orbitRankLocus {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    IsZariskiClosed (canonicalCoord d '' orbitRankLocus M) := by
  rw [IsZariskiClosed, image_orbitRankLocus_eq_zeroLocus M]
  exact (MvPolynomial.zeroLocus_vanishingIdeal_galoisConnection
    (σ := RepCoord d) (k := k) (K := k)).l_u_l_eq_l _ |>.symm

/-! ## The easy orbit inclusion `O_M ⊆ orbitRankLocus M` -/

/-- Every tuple in the orbit of `M` lies in `orbitRankLocus M`: a base change preserves the rank
pattern (`rankPattern_eq_of_smul`), so `rankPattern (P • M) = rankPattern M ≤ rankPattern M`. The
orbit (before flattening) is contained in the rank locus — the easy half of Thm 3.8. -/
theorem orbit_subset_orbitRankLocus {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    {A | ∃ P : BaseChangeGroup (k := k) d, P • M = A} ⊆ orbitRankLocus M := by
  rintro A ⟨P, rfl⟩ i j hij
  exact (rankPattern_eq_of_smul P rfl i j hij).symm.le

/-- **The orbit is contained in the rank locus (L6.3, flattened form).** `O_M = canonicalCoord ''
(orbit of M) ⊆ canonicalCoord '' orbitRankLocus M`: the orbit-invariance of the rank pattern places
every orbit point in the determinantal locus. With `isZariskiClosed_orbitRankLocus`, the Zariski
closure of `O_M` stays inside `orbitRankLocus M` — the easy inclusion `Ō_M ⊆ orbitRankLocus M`. -/
theorem orbitSet_subset_orbitRankLocus {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    orbitSet M ⊆ canonicalCoord d '' orbitRankLocus M :=
  Set.image_mono (orbit_subset_orbitRankLocus M)

/-- **The easy ideal inclusion.** `vanishingIdeal (canonicalCoord '' orbitRankLocus M) ≤
vanishingIdeal (O_M)`: at the ideal level the easy orbit inclusion `O_M ⊆ orbitRankLocus M` is the
*trivial* containment of vanishing ideals (`vanishingIdeal` is order-reversing). The genuine content
of L6.3 is the closedness `isZariskiClosed_orbitRankLocus`; this is the ideal-side shadow. -/
theorem vanishingIdeal_orbitRankLocus_le_orbitSet {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    MvPolynomial.vanishingIdeal k (canonicalCoord d '' orbitRankLocus M)
      ≤ MvPolynomial.vanishingIdeal k (orbitSet M) :=
  MvPolynomial.vanishingIdeal_anti_mono (orbitSet_subset_orbitRankLocus M)

section Witness

/-! ## Non-vacuity witnesses

The determinantal-rank bridge fires on a concrete rank-1 matrix; the rank locus is inhabited (every
`M` is in its own); the orbit inclusion is exercised on the `(2,2,2)/ℚ` orbit witness. -/

/-- The bridge fires concretely: the `2×2` zero matrix over `ℚ` has rank `≤ 0`, witnessed through
the bridge by every `1×1` minor (an entry) being `0`. -/
example : (0 : Matrix (Fin 2) (Fin 2) ℚ).rank ≤ 0 := by
  rw [rank_le_iff_forall_submatrix_det_eq_zero]
  intro er ec
  rw [Matrix.det_fin_one]
  simp

/-- Direction B fires concretely: the `2×2` identity over `ℚ` does not have rank `≤ 1` — its single
`2×2` minor (its determinant `1`) is nonzero. -/
example : ¬ (1 : Matrix (Fin 2) (Fin 2) ℚ).rank ≤ 1 := by
  rw [rank_le_iff_forall_submatrix_det_eq_zero]
  intro h
  have := h id id
  rw [Matrix.submatrix_id_id, Matrix.det_one] at this
  exact one_ne_zero this

/-- The rank locus is inhabited: every `M` lies in its own flattened rank locus. -/
example {d : Fin (N + 1) → ℕ} (M : Tuple (k := k) d) :
    canonicalCoord d M ∈ canonicalCoord d '' orbitRankLocus M :=
  ⟨M, self_mem_orbitRankLocus M, rfl⟩

/-- The orbit inclusion is non-vacuous: the `(2,2,2)/ℚ` orbit point `canonicalCoord tupleWitnessQ`
lies in `canonicalCoord '' orbitRankLocus tupleWitnessQ`. -/
example : canonicalCoord dWitness tupleWitnessQ
    ∈ canonicalCoord dWitness '' orbitRankLocus tupleWitnessQ :=
  orbitSet_subset_orbitRankLocus tupleWitnessQ
    ⟨tupleWitnessQ, ⟨1, one_smul _ _⟩, rfl⟩

end Witness

end DLNFibre.Core
